version: '3.1'
services:
    app:
        build:
            context: ./
        ports:
            - "8000:8000"
            - "8080:8080"
        container_name: app
        volumes:
            - ./:/app
        working_dir: /app
        #        command: /bin/bash
        stdin_open: true
        tty: true
        environment:
            VUE_APP_API_URL: 'http://194.182.69.216:9080'   #test API
#            VUE_APP_API_URL: 'http://194.182.69.216:8080'   #production API
#            VUE_APP_API_URL: 'https://e293028e-865b-47fe-b977-caa92669e275.mock.pstmn.io'   #postman mock API
