version: '3.1'
services:
    app:
        build:
            context: ./
        ports:
            - "8000:8000"
            - "8080:8080"
        container_name: app
        volumes:
            - ./:/app
        working_dir: /app
        #        command: /bin/bash
        stdin_open: true
        tty: true
